title: Everything about Cancer
author: Simon Tse
email: simonkamantse@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  Learn about cancer with Data and Code

# social links
github_username:  ghostintheshellarise

show_excerpts: true # set to false to remove excerpts on the homepage
